Devlabs\SportifyBundle\Entity\Match:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        datetime:
            expose: true
        homeTeamId:
            expose: true
            access_type: public_method
            accessor:
                getter: getHomeTeamName
            type: string
            serialized_name: home_team
        awayTeamId:
            expose: true
            access_type: public_method
            accessor:
                getter: getAwayTeamName
            type: string
            serialized_name: away_team
        homeGoals:
            expose: true
        awayGoals:
            expose: true
        tournamentId:
            expose: true
            access_type: public_method
            accessor:
                getter: getTournamentName
            type: string
            serialized_name: tournament
        notificationSent:
            expose: true
    relations:
        -
            rel: self
            href:
                route: get_match
                parameters:
                    id: expr(object.getId())
        -
            rel: home_team
            href:
                route: get_team
                parameters:
                    id: expr(object.getHomeTeamId().getId())
        -
            rel: away_team
            href:
                route: get_team
                parameters:
                    id: expr(object.getAwayTeamId().getId())
        -
            rel: tournament
            href:
                route: get_tournament
                parameters:
                    id: expr(object.getTournamentId().getId())
        -
            rel: predictions
            href:
                route: get_match_predictions
                parameters:
                    id: expr(object.getId())