Devlabs\SportifyBundle\Entity\Match:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        datetime:
            expose: true
        homeTeamId:
            expose: true
        awayTeamId:
            expose: true
        homeGoals:
            expose: true
        awayGoals:
            expose: true
        notificationSent:
            expose: true
    relations:
        -
            rel: self
            href:
                route: get_match
                parameters:
                    id: expr(object.getId())
        -
            rel: tournament
            href:
                route: get_tournament
                parameters:
                    id: expr(object.getTournamentId())
            embedded:
                content: expr(object.getTournamentId().getName())
        -
            rel: predictions
            href:
                route: get_match_predictions
                parameters:
                    id: expr(object.getId())