Devlabs\SportifyBundle\Entity\Tournament:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        startDate:
            expose: true
        endDate:
            expose: true
    relations:
        -
            rel: self
            href:
                route: get_tournament
                parameters:
                    id: expr(object.getId())
        -
            rel: scores
            href:
                route: get_tournament_scores
                parameters:
                    id: expr(object.getId())
        -
            rel: matches
            href:
                route: get_tournament_matches
                parameters:
                    id: expr(object.getId())
        -
            rel: teams
            href:
                route: get_tournament_teams
                parameters:
                    id: expr(object.getId())
        -
            rel: champ_predictions
            href:
                route: get_tournament_champ_predictions
                parameters:
                    id: expr(object.getId())