imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DevlabsSportifyBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # application parameters
    football_api.name: football_data_org
    football_api.base_uri: http://api.football-data.org/v1

framework:
    #esi:             ~
    translator: { fallbacks: [en] }
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
#    serializer:
#        enabled: true
#        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

#sensio_framework_extra:
#    request: { converters: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Devlabs\SportifyBundle\Entity\User
    registration:
        form:
            type: Devlabs\SportifyBundle\Form\RegistrationFormType
        confirmation:
            enabled: true
            template: templates/emails/registration.email.twig
    from_email:
        address:        "%mailer_sender_address%"
        sender_name:    Sportify
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        form:
            type: Devlabs\SportifyBundle\Form\ResettingFormType
        email:
            template: templates/emails/password_resetting.email.twig
    change_password:
        form:
            type: Devlabs\SportifyBundle\Form\ChangePasswordFormType

fos_rest:
    zone:
        - { path: ^/api/* }
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    body_listener:
        enabled:              true
        array_normalizer: fos_rest.normalizer.camel_keys
#        decoders:
#            json: fos_rest.decoder.jsontoform
#    body_converter:
#        enabled:              true
#        validate:             true
#        validation_errors_argument:  validationErrors
    view:
        view_response_listener: force
        formats:
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
    serializer:
        version: null
        groups: []
        serialize_null: true
    disable_csrf_role: ROLE_API
    exception:
#        codes:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#        messages:
#            'ddasd': true
#        enabled: true
#        exception_controller: 'Devlabs\SportifyBundle\Controller\Base\ExceptionController::showAction'

jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                path: "%kernel.root_dir%/config/serializer/FOSUB"
                namespace_prefix: "FOS\\UserBundle"
            DevlabsSportifyBundle:
                path: "%kernel.root_dir%/config/serializer/DevlabsSportify"
                namespace_prefix: "Devlabs\\SportifyBundle"

bazinga_hateoas:
    metadata:
        cache: file
        file_cache:
            dir: %kernel.cache_dir%/hateoas

fos_oauth_server:
    db_driver: orm
    client_class:        Devlabs\SportifyBundle\Entity\OAuthClient
    access_token_class:  Devlabs\SportifyBundle\Entity\OAuthAccessToken
    refresh_token_class: Devlabs\SportifyBundle\Entity\OAuthRefreshToken
    auth_code_class:     Devlabs\SportifyBundle\Entity\OAuthAuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            access_token_lifetime: 7776000 # 90 days in seconds

nelmio_api_doc: ~