services:
#    devlabs_sportify.example:
#        class: Devlabs\SportifyBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    app.form.type.prediction:
        class: Devlabs\SportifyBundle\Form\PredictionType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
