devlabs_sportify:
    resource: "@DevlabsSportifyBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@DevlabsSportifyBundle/Resources/config/routing/all.xml"