# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: Devlabs\SportifyBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.resetting:
        class: Devlabs\SportifyBundle\Form\ResettingFormType
        tags:
            - { name: form.type, alias: app_user_resetting }
    app.form.change_password:
        class: Devlabs\SportifyBundle\Form\ChangePasswordFormType
        tags:
            - { name: form.type, alias: app_user_changepassword }
    app.slack:
        class: Devlabs\SportifyBundle\Services\Slack

    app.score_updater:
        class: Devlabs\SportifyBundle\Services\ScoreUpdater
        arguments: ['@service_container']

    app.filter.helper:
        class: Devlabs\SportifyBundle\Services\FilterHelper
        arguments: ['@service_container']

    app.matches.helper:
        class: Devlabs\SportifyBundle\Services\MatchesHelper
        arguments: ['@service_container']

    app.history.helper:
        class: Devlabs\SportifyBundle\Services\HistoryHelper
        arguments: ['@service_container']

    app.champion.helper:
        class: Devlabs\SportifyBundle\Services\ChampionHelper
        arguments: ['@service_container']

    app.tournaments.helper:
        class: Devlabs\SportifyBundle\Services\TournamentsHelper
        arguments: ['@service_container']

    app.data_updates.manager:
        class: Devlabs\SportifyBundle\Services\DataUpdates\Manager
        arguments: ['@service_container']

    app.data_updates.importer:
        class: Devlabs\SportifyBundle\Services\DataUpdates\Importer
        arguments: ['@service_container']

    app.data_updates.fetchers.football_data_org:
        class: Devlabs\SportifyBundle\Services\DataUpdates\Fetchers\FootballDataOrg

    app.data_updates.parsers.football_data_org:
        class: Devlabs\SportifyBundle\Services\DataUpdates\Parsers\FootballDataOrg
